### ISSUE TITLE
Question. Not issue

### ISSUE THREAD

**Issue by Kaily001** [chiteroman/Reprogram-TEE-on-Qualcomm-devices#18]
""This guide will NOT provide instructions for passing Strong verdict.""

might i just ask why? 

and where can i?

--if u can i what to know if its in ANY way possible to pass Strong intergrety --> eg.  Have FULL Memory accses 
preferably on a android google pixel 8 pro --> but any phone runing android 13 and over is fine too

and i know 90% or so of apps don't require strong integretiy but im here to prove a point to google
--i will do ANYTHING necessary I Will solder off the Memory chip if i have to I am willing to do iriversiable damage if it has even a small chance of working

**Comment by PhantomHydraPH** [comment]
Try a module called TrickyStore, it may help you pass strong depending on your ROM.

**Comment by Kaily001** [comment]
Pass STONG INTEGRITY now Thx so much

**Comment by Sheisterrific** [comment]
Are you rooted, and what with?  Why do you want STRONG this much?  If you are on a custom, which one and version?  Finally, what is the meat of your solution?  Any info is helpful, and all info is preferred!  😀

**Comment by Kaily001** [comment]
I am rooted w magisk and I don't understand your questions?
I seem to have awnserd the why previously and Ikw what meat of your solution means kina sound like a bot or smt and I marked as completed as I got what I wanted and my question was awnserd Ikw what I doing here

**Comment by Kaily001** [comment]
I reopened and closed so that you can see it

**Comment by Sheisterrific** [comment]
Are you from the subcontinent?  Your English is... bizarre.  Anyway, I was hoping you collected scientific information.  Making any custom ROM to pass STRONG is not supposed to be possible.  If somehow you fell into someone else's solution, I only want the details of their work that you think "solved it."  Hence, my request for details.  Cheers.

**Comment by Kaily001** [comment]
Wat yea u can it's called hacking TEE
Bozo

**Comment by Kaily001** [comment]
> Are you from the subcontinent? Your English is... bizarre. Anyway, I was hoping you collected scientific information. Making any custom ROM to pass STRONG is not supposed to be possible. If somehow you fell into someone else's solution, I only want the details of their work that you think "solved it." Hence, my request for details. Cheers.

Also don't call my English bizarre ya brit 
USA is proper English and who says subcontinent only Brits bro only em Brits
