### ISSUE TITLE
InstallKeybox Failed , Any help?

### ISSUE THREAD

**Issue by Xeno761** [chiteroman/Reprogram-TEE-on-Qualcomm-devices#2]
Throws error on last step , check attached photo
![IMG_20240104_235830_675](https://github.com/chiteroman/Reprogram-TEE-on-Qualcomm-devices/assets/67216393/194e357f-43dc-4a11-91d1-db3f2f68443b)

**Comment by Xeno761** [comment]
Fixed when executed through termux

**Comment by mizuhashikuniumi** [comment]
can you help me guide for termux?

**Comment by AnwarShah** [comment]
Where do I get the device id of my device?
