### ISSUE TITLE
error -10004, help me what this code

### ISSUE THREAD

**Issue by mizuhashikuniumi** [chiteroman/Reprogram-TEE-on-Qualcomm-devices#3]
LD_LIBRARY_PATH=/vendor/lib64/hw KmInstallKeybox keybox.xml X705F100000000 false                                       <
Number of keyboxes 1
myDeviceID: X705F100000000
keyboxCtx.device_id.data: X705F100000000
KeyMasterInstallKeybox error-10004
InstallKeybox Failed!-2000
48|surya:/data/nativetest64/qti_keymaster_tests #

**Comment by chiteroman** [comment]
Try:

> qseecom_sample_client v smplap64 14 1

Write 1 and enter. Then check again if you can write key.

**Comment by chetan17289** [comment]
> Try:
> 
> > qseecom_sample_client v smplap64 14 1
> 
> Write 1 and enter. Then check again if you can write key.

keyboxCtx.device_id.data: X705F100000000
KeyMasterInstallKeybox error-10004
InstallKeybox Failed!
Destructor

qseecom_sample_client v smplap64 14 1

RPMB key provisioning failed (-1)

**Comment by chiteroman** [comment]
Uh, maybe your TEE is permantly broken. This is weird...

**Comment by heshamgazzaz** [comment]
> Try:
> 
> > qseecom_sample_client v smplap64 14 1
> 
> Write 1 and enter. Then check again if you can write key.

RPMB key provisioning failed (-1)
