### ISSUE TITLE
About keybox

### ISSUE THREAD

**Issue by zfdx123** [chiteroman/Reprogram-TEE-on-Qualcomm-devices#6]
Hello, dear developer, first of all, thank you for saving many tee damaged users. May I ask if the certificate inside keybox can be generated by yourself? If I can, I hope to get the generation method. Thank you, dear developer.

**Comment by TechnoPhysics** [comment]
> Hello, dear developer, first of all, thank you for saving many tee damaged users. May I ask if the certificate inside keybox can be generated by yourself? If I can, I hope to get the generation method. Thank you, dear developer.

Dude even I am interested for it BECAUSE CURRENT KEYS are blacklisted

**Comment by anggialansori404** [comment]
> > Hello, dear developer, first of all, thank you for saving many tee damaged users. May I ask if the certificate inside keybox can be generated by yourself? If I can, I hope to get the generation method. Thank you, dear developer.
> 
> Dude even I am interested for it BECAUSE CURRENT KEYS are blacklisted

Waiting for another keybox

**Comment by TechnoPhysics** [comment]
Waiting for another keybox or ways to fix it permanently

**Comment by TechnoPhysics** [comment]
> > > Hello, dear developer, first of all, thank you for saving many tee damaged users. May I ask if the certificate inside keybox can be generated by yourself? If I can, I hope to get the generation method. Thank you, dear developer.
> > 
> > 
> > Dude even I am interested for it BECAUSE CURRENT KEYS are blacklisted
> 
> Waiting for another keybox

Yeah

**Comment by chiteroman** [comment]
All public keybox are blacklisted.

There is no way to generate by yourself a keybox.

More info here: https://xdaforums.com/t/cts-doesnt-pass-even-with-locked-bootloader.4522643/post-89299394
