### ISSUE TITLE
ask blacklist attestantion

### ISSUE THREAD

**Issue by htndbr** [chiteroman/Reprogram-TEE-on-Qualcomm-devices#8]
hi,
how to check a keybox banned or not?
is there a way to check if keybox banned or not in enginering rom?

i don't plan to lock bootloader can i leave tee broken?
are there any negative impact?

**Comment by VisionR1** [comment]
> hi, how to check a keybox banned or not? is there a way to check if keybox banned or not in enginering rom?
> 
> i don't plan to lock bootloader can i leave tee broken? are there any negative impact?

https://xdaforums.com/t/module-play-integrity-fix-safetynet-fix.4607985/post-89393099
